# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, httpConduit, httpTypes, mtl, text, time
, unorderedContainers, utf8String
}:

cabal.mkDerivation (self: {
  pname = "stripe";
  version = "0.8.1";
  src = ./.;
  buildDepends = [
    aeson httpConduit httpTypes mtl text time unorderedContainers
    utf8String
  ];
  jailbreak = true;
  meta = {
    homepage = "https://github.com/michaelschade/hs-stripe";
    description = "A Haskell implementation of the Stripe API";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ ocharles ];
  };
})
